/* eslint-disable prettier/prettier */
// Generated by https://quicktype.io

export interface PokeAPI {
  count:    number;
  next:     string;
  previous: null;
  results:  Result[];
}

export interface Result {
  name: string;
  url:  string;
}
